### PR TITLE
Add allRawValues return allRaws value with all values initialised

### PR DESCRIPTION
**Pull request by volatilegg**
Hi, I just tried using this today, and like it very much. Thanks for this.

Just one minor thing that's bugging me, remember to call `initialized()` before fetching `allRaws` like you have mentioned in README

Here's my purpose to fix that issue.

### CODE REVIEW

**Comment by polac24** [comment]
Thanks @volatilegg for this change!
You are right and we can make API more convenient without this requirement of `initailize()`! 🎉 

In order to accept this change, can you:
* make `initialize` function private (at least invisible to the public API), as it is not required anymore?
* add/modify existing unit tests to cover this change? If you don't feel comfortable with unit tests, let me know and I will try to update it on my own.
* Update README.md file to not mention about not-required-anymore `initailize`?

Thanks again!

**Comment by volatilegg** [comment]
@polac24 Yes, I can fix those this weekend 👍

**Comment by volatilegg** [comment]
@polac24 I have updated the branch with

- [x] make initialize function private (at least invisible to the public API)
- [x] modify existing unit tests to cover this change, test coverage has gone back to 100%. Although my test writing skill is awful, please knock your self out if you find any horrible stuff
- [x] Update README.md file to not mention about not-required-anymore initailize

**Comment by polac24** [comment]
Thanks a lot, @volatilegg!

**Pull request merged**
